name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '新功能 ✨'
    labels:
      - 'feature'
  - title: '修复 🐛'
    labels:
      - 'bug'
  - title: '优化 ⚡️'
    labels:
      - 'perf'  # 确保标签名称一致
change-template: '- $TITLE (#$NUMBER) @${{PRAUTHOR}}'
no-changes-template: '- 没有变化'
template: |
  ## v$NEXT_PATCH_VERSION 🌟

  {% if categories['新功能 ✨'] %}
  ## 新功能 ✨
  {{categories['新功能 ✨']}}
  {% endif %}

  {% if categories['修复 🐛'] %}
  ## 修复 🐛
  {{categories['修复 🐛']}}
  {% endif %}

  {% if categories['优化 ⚡️'] %}
  ## 优化 ⚡️
  {{categories['优化 ⚡️']}}
  {% endif %}
