services:
  mongo:
    container_name: ${CONTAINER_NAME_PREFIX}_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    ports:
      - 27018:27017
    volumes:
      - ${RESOURCE_DB_PATH}/data/db:/data/db
      - ${RESOURCE_DB_PATH}/custom:/etc/mongo
      - ${RESOURCE_DB_PATH}/backup:/dump
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  jmalcloud:
    container_name: ${CONTAINER_NAME_PREFIX}_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    ports:
      - ${SERVER_PORT}:8088
      - ${FTP_SERVER_PORT}:8089
    volumes:
      - ${RESOURCE_FILE_PATH}:/jmalcloud/files/
    restart: always
  nginx:
    container_name: ${CONTAINER_NAME_PREFIX}_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - ${APP_PORT}:80
      - ${BLOG_PORT}:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: always
  office:
    container_name: ${CONTAINER_NAME_PREFIX}_office
    image: onlyoffice/documentserver:${OFFICE_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
  drawio-webapp:
    container_name: ${CONTAINER_NAME_PREFIX}_drawio
    image: jgraph/drawio:${DRAWIO_IMAGE_VERSION}
    environment:
      TZ: Asia/Shanghai
    restart: always
networks: {}
