server:
  port: 8088
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
version: 2.7.0
spring:
  application:
    name: jmalcloud
  main:
    allow-circular-references: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=3600s
springdoc:
  packages-to-scan: com.jmal.clouddisk.controller,com.jmal.clouddisk.oss
  api-docs:
    path: /public/api-docs
  swagger-ui:
    path: /public/api
    doc-expansion: none
