spring:
  thymeleaf: # thymeleaf配置，开发环境不启用缓存，正式环境下请启用缓存，提高性能
    cache: false
    mode: HTML # thymeleaf对html元素格式要求严格，设置它的mode为HTML，忘记结束标签后不会报错
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/jmalcloud
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
      chain:
        cache: false
tess4j:
  # tess4j ocr path
  data-path: /Users/jmal/studio/myProject/github/jmal-cloud-server/tess4j/datapath
logging:
  level:
    root: info
