name: Build jdk17_ffmpeg_nvidia

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 and Maven 3.8.4
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          maven-version: '3.8.4'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Extract project version from pom.xml
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: jmal/jdk17_ffmpeg_nvidia:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            ARCH=${{ matrix.arch }}
    strategy:
      matrix:
        arch: [amd64, arm64]
