name: Create Release with Jar

on:
  push:
    branches:
      - release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Extract project version from pom.xml
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          git fetch --prune --unshallow
          LATEST_TAG=$(git describe --tags --abbrev=0)
          FEAT_MSGS=$(git log $LATEST_TAG..HEAD --grep 'feat:' --pretty=format:"- %s%n" | sed 's/feat://')
          FIX_MSGS=$(git log $LATEST_TAG..HEAD --grep 'fix:' --pretty=format:"- %s%n" | sed 's/fix://')
          PERF_MSGS=$(git log $LATEST_TAG..HEAD --grep 'perf:' --pretty=format:"- %s%n" | sed 's/perf://')
          RELEASE_NOTES=""
          if [ -n "$FEAT_MSGS" ]; then
            RELEASE_NOTES+="### 新功能 ✨\n${FEAT_MSGS}\n"
          fi
          if [ -n "$FIX_MSGS" ]; then
            RELEASE_NOTES+="### 修复 🐛\n${FIX_MSGS}\n"
          fi
          if [ -n "$PERF_MSGS" ]; then
            RELEASE_NOTES+="### 优化 🎨\n${PERF_MSGS}\n"
          fi
          echo -e "RELEASE_NOTES<<EOF\n$RELEASE_NOTES\nEOF" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a v${{ env.PROJECT_VERSION }} -m "v${{ env.PROJECT_VERSION }}"
          git push origin v${{ env.PROJECT_VERSION }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PROJECT_VERSION }}
          release_name: v${{ env.PROJECT_VERSION }}
          body: |
            ## Changes in this release:
            ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false

      - name: Upload Jar to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/clouddisk-${{ env.PROJECT_VERSION }}.jar
          asset_name: clouddisk-${{ env.PROJECT_VERSION }}.jar
          asset_content_type: application/java-archive
